wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.15
    cli_version: 0.16.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1733637149.950373
    t:
      1:
      - 12
      - 45
      - 55
      2:
      - 12
      - 45
      - 55
      3:
      - 23
      4: 3.10.15
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
'?':
  desc: null
  value: false
alsologtostderr:
  desc: null
  value: false
batch_size:
  desc: null
  value: 256
chex_assert_multiple_cpu_devices:
  desc: null
  value: false
chex_n_cpu_devices:
  desc: null
  value: 1
chex_skip_pmap_variant_if_single_device:
  desc: null
  value: true
config:
  desc: null
  value: 'actor_lr: 0.0003

    backup_entropy: false

    critic_layer_norm: true

    critic_lr: 0.0003

    discount: 0.99

    hidden_dims: !!python/tuple

    - 256

    - 256

    - 256

    init_temperature: 1.0

    model_cls: SACLearner

    num_min_qs: 2

    num_qs: 10

    target_entropy: null

    tau: 0.005

    temp_lr: 0.0003

    '
config.backup_entropy:
  desc: null
  value: false
config.init_temperature:
  desc: null
  value: 1.0
config.num_min_qs:
  desc: null
  value: 2
debug:
  desc: null
  value: false
dynamics_config:
  desc: null
  value: 'dropout_rate: 0.1

    hidden_dims: !!python/tuple

    - 256

    - 256

    learning_rate: 0.0003

    model_cls: DynamicsModel

    weight_decay: 0.0

    '
env_name:
  desc: null
  value: kitchen-partial-v0
eval_episodes:
  desc: null
  value: 10
eval_interval:
  desc: null
  value: 10000
experimental_orbax_use_distributed_process_id:
  desc: null
  value: false
help:
  desc: null
  value: false
helpfull:
  desc: null
  value: false
helpshort:
  desc: null
  value: false
helpxml:
  desc: null
  value: false
hpolicy_horizon:
  desc: null
  value: 4
interpolate:
  desc: null
  value: false
load_dir:
  desc: null
  value: ./opal_checkpoints
log_dir:
  desc: null
  value: ''
log_interval:
  desc: null
  value: 1000
logger_levels:
  desc: null
  value: {}
logtostderr:
  desc: null
  value: false
max_steps:
  desc: null
  value: 300000
offline_ratio:
  desc: null
  value: 0.5
offline_relabel_type:
  desc: null
  value: pred
only_check_args:
  desc: null
  value: false
opal_config:
  desc: null
  value: "beta_coef: 0.25\ndiscount: 0.99\niql:\n  critic_layer_norm: false\n  discount:\
    \ 0.99\n  expectile: 0.9\n  faster_actor_update: false\n  hidden_dims: !!python/tuple\n\
    \  - 256\n  - 256\n  lr: 0.0003\n  num_qs: 2\n  policy_extraction: awr\n  tau:\
    \ 0.005\n  temperature: 1.0\nkl_coef: 0.1\nlatent_dim: 50\nlr: 0.0003\nskill_dim:\
    \ 8\nvae_encoder_hidden_size: 256\nvae_hidden_dims: !!python/tuple\n- 256\n- 256\n"
pdb:
  desc: null
  value: false
pdb_post_mortem:
  desc: null
  value: false
profile_file:
  desc: null
  value: null
project_name:
  desc: null
  value: supe
rm_config:
  desc: null
  value: 'hidden_dims: !!python/tuple

    - 256

    - 256

    - 256

    lr: 0.0003

    model_cls: RM

    '
rnd_config:
  desc: null
  value: 'coeff: 8.0

    hidden_dims: !!python/tuple

    - 256

    - 256

    - 256

    lr: 0.0003

    model_cls: RND

    '
run_with_pdb:
  desc: null
  value: false
run_with_profiling:
  desc: null
  value: false
save_video:
  desc: null
  value: false
seed:
  desc: null
  value: 2
showprefixforinfo:
  desc: null
  value: true
start_training:
  desc: null
  value: 5000
stderrthreshold:
  desc: null
  value: fatal
test_random_seed:
  desc: null
  value: 301
test_randomize_ordering_seed:
  desc: null
  value: ''
test_srcdir:
  desc: null
  value: ''
test_tmpdir:
  desc: null
  value: /scratch/1030375/absl_testing
tqdm:
  desc: null
  value: true
updates_per_step:
  desc: null
  value: 4
use_cprofile_for_profiling:
  desc: null
  value: true
use_rnd_offline:
  desc: null
  value: true
use_rnd_online:
  desc: null
  value: true
utd_ratio:
  desc: null
  value: 20
v:
  desc: null
  value: -3
verbosity:
  desc: null
  value: -3
xml_output_file:
  desc: null
  value: ''
